//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ukagaka.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BootingConverterInverseType {
            get {
                return ((bool)(this["BootingConverterInverseType"]));
            }
            set {
                this["BootingConverterInverseType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BootingConverterThumbnail {
            get {
                return ((bool)(this["BootingConverterThumbnail"]));
            }
            set {
                this["BootingConverterThumbnail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BootingConverterZeropointBalloon {
            get {
                return ((bool)(this["BootingConverterZeropointBalloon"]));
            }
            set {
                this["BootingConverterZeropointBalloon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MailcheckServer {
            get {
                return ((string)(this["MailcheckServer"]));
            }
            set {
                this["MailcheckServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MailcheckUsername {
            get {
                return ((string)(this["MailcheckUsername"]));
            }
            set {
                this["MailcheckUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MailcheckPassword {
            get {
                return ((string)(this["MailcheckPassword"]));
            }
            set {
                this["MailcheckPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MailcheckCheckEnable {
            get {
                return ((bool)(this["MailcheckCheckEnable"]));
            }
            set {
                this["MailcheckCheckEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MailcheckCheckAutocheck {
            get {
                return ((bool)(this["MailcheckCheckAutocheck"]));
            }
            set {
                this["MailcheckCheckAutocheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MailcheckAutocheckInterval {
            get {
                return ((int)(this["MailcheckAutocheckInterval"]));
            }
            set {
                this["MailcheckAutocheckInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SstpSwitch {
            get {
                return ((bool)(this["SstpSwitch"]));
            }
            set {
                this["SstpSwitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SstpPort {
            get {
                return ((int)(this["SstpPort"]));
            }
            set {
                this["SstpPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DisplayLevelselect {
            get {
                return ((int)(this["DisplayLevelselect"]));
            }
            set {
                this["DisplayLevelselect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DisplayFontname {
            get {
                return ((string)(this["DisplayFontname"]));
            }
            set {
                this["DisplayFontname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DisplayFontsize {
            get {
                return ((int)(this["DisplayFontsize"]));
            }
            set {
                this["DisplayFontsize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DisplaySliderTransparency {
            get {
                return ((double)(this["DisplaySliderTransparency"]));
            }
            set {
                this["DisplaySliderTransparency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DisplayBalloonWaitRate {
            get {
                return ((double)(this["DisplayBalloonWaitRate"]));
            }
            set {
                this["DisplayBalloonWaitRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisplayBalloonFadeout {
            get {
                return ((bool)(this["DisplayBalloonFadeout"]));
            }
            set {
                this["DisplayBalloonFadeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisplayBalloonClickthrough {
            get {
                return ((bool)(this["DisplayBalloonClickthrough"]));
            }
            set {
                this["DisplayBalloonClickthrough"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DisplayGhostmanagerPreviewFilepath {
            get {
                return ((string)(this["DisplayGhostmanagerPreviewFilepath"]));
            }
            set {
                this["DisplayGhostmanagerPreviewFilepath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MiscAlwaysShowVanish {
            get {
                return ((bool)(this["MiscAlwaysShowVanish"]));
            }
            set {
                this["MiscAlwaysShowVanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MiscDeleteAfterOnlineInstall {
            get {
                return ((bool)(this["MiscDeleteAfterOnlineInstall"]));
            }
            set {
                this["MiscDeleteAfterOnlineInstall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MiscLoadWholeSurfacesOnBootingSurfaceServer {
            get {
                return ((bool)(this["MiscLoadWholeSurfacesOnBootingSurfaceServer"]));
            }
            set {
                this["MiscLoadWholeSurfacesOnBootingSurfaceServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MiscDisableSerikoAnimation {
            get {
                return ((bool)(this["MiscDisableSerikoAnimation"]));
            }
            set {
                this["MiscDisableSerikoAnimation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MiscShowDevInterfaces {
            get {
                return ((bool)(this["MiscShowDevInterfaces"]));
            }
            set {
                this["MiscShowDevInterfaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MiscLightmodeOnSstp {
            get {
                return ((bool)(this["MiscLightmodeOnSstp"]));
            }
            set {
                this["MiscLightmodeOnSstp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MiscResetSurfaceOnSstp {
            get {
                return ((bool)(this["MiscResetSurfaceOnSstp"]));
            }
            set {
                this["MiscResetSurfaceOnSstp"] = value;
            }
        }
    }
}
